Домашняя работа №3
red-beeard/FocusStartHomeworks pull request #4
Opened 2021-11-15 19:36 UTC by red-beeard

Создал три экрана про себя. Использовал scrollView, отдельные элементы ui. Всё в моделях.

P.S. Магические значения ещё не исправил. Завтра поправлю

2021-11-16 05:39 UTC, c0dedbear requested changes
В целом все хорошо, аккуратно сделано. У меня кстати друзья в Ростове живут) Они с ДВ переехали туда)

Смотри замечания по коду.

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/UIElement/ConcertView.swift
> +    var imageView = UIImageView()
почему не private?

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/UIElement/ConcertView.swift
> +        artistLabel.font = UIFont.boldSystemFont(ofSize: 25)
размер шрифта в метрики вынеси

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/UIElement/ConcertView.swift
> +            imageView.topAnchor.constraint(equalTo: self.safeAreaLayoutGuide.topAnchor, constant: 20),
отступы тоже в enum c метриками

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/ViewControllers/AboutMeViewController.swift
> +    var person: Person!
зачем здесь и в других местах в данных опционал?

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/ViewControllers/AboutMeViewController.swift
> +    private var avatarImageView: UIImageView!
здесь тоже не нужны опционалы и var

2021-11-16 05:39 UTC, c0dedbear commented on myCV/myCV/ViewControllers/HobbyViewController.swift
> +            result.append(ConcertView(concert: concert))
заюзай лучше .map

2021-11-16 15:43 UTC, red-beeard commented on myCV/myCV/UIElement/ConcertView.swift
> +    var imageView = UIImageView()
Я оставил его открытым, чтобы иметь доступ извне, как некоторых элементов. Возможно лучше закрыть его, а если нужно будет, то открыть.

2021-11-17 07:05 UTC, c0dedbear requested changes

2021-11-17 07:05 UTC, c0dedbear commented on myCV/myCV/ViewControllers/AboutMeViewController.swift
> +    var person: Person!
Какой смысл? У тебя данные захардкожены.

2021-11-17 07:05 UTC, c0dedbear commented on myCV/myCV/UIElement/ConcertView.swift
> +    var imageView = UIImageView()
В реальной разработке как правило все делается через интерефейсы - протоколы, и все свойства внутри закрыты для доступа извне. Ты можешь выхватить кучу сайд-эффектов если у тебя из разных мест будут дергаться эти свойства.

2021-11-17 16:32 UTC, c0dedbear commented
Принято

2021-11-17 16:32 UTC, merged