Домашняя работа №4
red-beeard/FocusStartHomeworks pull request #7
Opened 2021-11-20 10:28 UTC by red-beeard

Сделал приложение с collectionView на flowLayout

2021-11-21 14:33 UTC, c0dedbear requested changes
Все экраны хорошо смотрятся во всех ориентациях. 👍

Но при первом скролле происходит заметный такой фриз (ищи проблему в местах где сетаешь данные или считаешь layout)

Почти везде не хватает final у классов и местами маг цифры.

2021-11-21 14:33 UTC, c0dedbear commented on CollectionApp/CollectionApp/Model/Image.swift
> +        DataManager.shared.images.map { (key, value) in
Зачем это оверхед с синглотоном, который вызывается только здесь? У тебя статические данные зачем тебе сдался какой то менеджер. Перемести свой словарик сюда и удали это недоменджер.

2021-11-21 14:33 UTC, c0dedbear commented on CollectionApp/CollectionApp/ViewControllers/DetailsViewController.swift
> +        self.stackView.spacing = 8
маг цифра

2021-11-21 14:38 UTC, red-beeard commented
Миша, а может быть это связано с тем, что у меня картинки в разрешении 4000 на 5000 почти все и не сжаты? Типа ему тяжело их закинуть в переиспользуемую ячейку или что-то вроде того

2021-11-22 15:59 UTC, c0dedbear commented
> Миша, а может быть это связано с тем, что у меня картинки в разрешении 4000 на 5000 почти все и не сжаты? Типа ему тяжело их закинуть в переиспользуемую ячейку или что-то вроде того

вполне

2021-11-22 17:46 UTC, c0dedbear commented
> Попробовать написать resize именно для этого экрана? Или пока оставить так. Остальные правки сейчас сделаю и запушу

Если интересно разберись. Так как у тебя статика ты можешь просто уменьшенные версии положить в ассеты. А так на будущее имей ввиду что тяжелые картинки в коллекциях/таблицах не используют, их наоборот максимально оптимизируют под разные экраны, даже несколько килобайт разницы в пересчете на бесконечные скроллы (аля Инстаграм и вк) будут иметь значимость.

Аппрув ставлю вообщем.

2021-11-22 17:47 UTC, c0dedbear approved these changes
Принято

2021-11-22 17:47 UTC, merged